name: Release Mobile App

on:
  workflow_call:
    inputs:
      build-target:
        description: 'Build Target'
        type: string
        required: true
      build-type:
        description: 'Build Type'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      build-target:
        description: 'Build Target'
        type: choice
        required: true
        default: distribution
        options:
          - development
          - distribution
      build-type:
        description: 'Build Type'
        type: choice
        required: true
        default: canary
        options:
          - canary
          - beta
          - stable
env:
  BUILD_TYPE: ${{ inputs.build-type || github.event.inputs.build-type }}
  BUILD_TARGET: ${{ inputs.build-target || github.event.inputs.build-target }}
  DEBUG: napi:*
  KEYCHAIN_NAME: ${{ github.workspace }}/signing_temp

jobs:
  output-env:
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ steps.env.outputs.ENVIRONMENT }}
    steps:
      - name: Output Environment
        id: env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "ENVIRONMENT=${{ github.event.inputs.build-type }}" >> $GITHUB_OUTPUT
          else
            echo "ENVIRONMENT=" >> $GITHUB_OUTPUT
          fi

  build-android-web:
    runs-on: ubuntu-24.04-arm
    needs:
      - output-env
    environment: ${{ needs.output-env.outputs.ENVIRONMENT }}
    outputs:
      RELEASE_VERSION: ${{ steps.version.outputs.APP_VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Version
        id: version
        uses: ./.github/actions/setup-version
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
      - name: Setup @sentry/cli
        uses: ./.github/actions/setup-sentry
      - name: Build Mobile
        run: yarn affine @affine/android build
        env:
          PUBLIC_PATH: '/'
          MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: 'affine'
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_RELEASE: ${{ steps.version.outputs.APP_VERSION }}
          RELEASE_VERSION: ${{ steps.version.outputs.APP_VERSION }}
      - name: Upload android artifact
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: packages/frontend/apps/android/dist

  android:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
    needs:
      - build-android-web
    steps:
      - uses: actions/checkout@v4
      - name: Setup Version
        id: version
        uses: ./.github/actions/setup-version
      - name: Download mobile artifact
        uses: actions/download-artifact@v4
        with:
          name: android
          path: packages/frontend/apps/android/dist
      # - name: Load Google Service file
      #   env:
      #     DATA: ${{ secrets.FIREBASE_ANDROID_GOOGLE_SERVICE_JSON }}
      #   run: echo $DATA | base64 -di > packages/frontend/apps/android/App/app/google-services.json
      - name: Inject dummy google-services.json
        run: |
          mkdir -p packages/frontend/apps/android/App/app
          cat > packages/frontend/apps/android/App/app/google-services.json <<EOF
          {
            "project_info": {
              "project_number": "123456789",
              "project_id": "dummy-project"
            },
            "client": [],
            "configuration_version": "1"
          }
          EOF
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        timeout-minutes: 10
        with:
          extra-flags: workspaces focus @affine/monorepo @affine-tools/cli @affine/android @affine/playstore-auto-bump
          playwright-install: false
          electron-install: false
          hard-link-nm: false
          enableScripts: false
      - name: Setup Rust
        uses: ./.github/actions/build-rust
        with:
          target: 'aarch64-linux-android'
          package: 'affine_mobile_native'
          no-build: 'true'
      - name: Cap sync
        run: yarn workspace @affine/android cap sync
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Build
        run: |
          echo -n "${{ env.AFFINE_ANDROID_SIGN_KEYSTORE }}" | base64 --decode > packages/frontend/apps/android/affine.keystore
          yarn workspace @affine/android cap build android --flavor ${{ env.BUILD_TYPE }} --androidreleasetype AAB
        env:
          AFFINE_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.AFFINE_ANDROID_KEYSTORE_PASSWORD }}
          AFFINE_ANDROID_KEYSTORE_ALIAS_PASSWORD: ${{ secrets.AFFINE_ANDROID_KEYSTORE_ALIAS_PASSWORD }}
          AFFINE_ANDROID_SIGN_KEYSTORE: ${{ secrets.AFFINE_ANDROID_SIGN_KEYSTORE }}
          VERSION_NAME: ${{ steps.version.outputs.APP_VERSION }}
      - name: Build APK
        run: |
          cd packages/frontend/apps/android/App
          ./gradlew assembleRelease
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: affine-apk
          path: packages/frontend/apps/android/App/app/build/outputs/apk/release/app-release.apk

